version: '3.8'

services:
  frontend:
    build:
      context: ./optidecision_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./optiDecisionBackend
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./optiDecisionBackend:/app
      - ./optiDecisionBackend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
